[package]
name = "ps-hash"
version = "0.1.0-12"
edition = "2021"
description = "Generates 64-byte ascii hashes with 256 bits of security."
license = "GPL-3.0-or-later"

[dependencies]
blake3 = "1.8.2"
ps-base64 = "0.1.0-5"
ps-buffer = "0.1.0-18"
ps-ecc = "0.1.0-3"
ps-pint16 = "0.1.0-4"
sha2 = "0.10.9"
thiserror = "2.0.12"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
