[package]
name = "ps-hash"
version = "0.1.0-4"
description = "Generates 50-byte hashes with 256 bits of security."
license = "GPL-3.0-or-later"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
blake3 = "1.5.0"
ps-base64 = "0.1.0-2"
sha2 = "0.10.8"
