[package]
name = "ps-hash-core"
version.workspace = true
edition.workspace = true
description = "Core hashing primitives for ps-hash."
repository.workspace = true
license.workspace = true

[dependencies]
blake3 = "1.8.5"
ps-base64 = "0.1.0-7"
ps-crockford32 = "0.1.0-1"
ps-ecc = "0.1.0-9"
ps-pint16 = "0.1.0-5"
ps-util = "0.1.0-9"
sha2 = "0.11.0"
thiserror = "2.0.19"
